version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: my-php-site-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    restart: unless-stopped